---
title: "preparation"
author: "Reilly Amera"
date: "2025-02-26"
output: html_document
---

```{r setup}
#install.packages("eeptools") 
#used for birthday -> age. Found out about this from a YouTube video
library(eeptools)
library(tidyverse)
install.packages("mediation")
library(mediation)
```

```{r read-in}
child <- read_csv("child.csv", col_names = TRUE)
parent <- read_csv("parent.csv", col_names = TRUE)
```

```{r cleaning}
# removing unnecessary columns
child <- child %>% 
  select(-c(1:5, 8:18))
child <- child[-c(1, 2),]

parent <- parent %>% 
  select(-c(1:6, 8:18))
parent <- parent[-c(1),]

# replacing one NA (participant forgot ID)
child$PID[is.na(child$PID)] <- 1

# renaming 'finished' columns 
child <- child %>% 
  rename(Cfinished = Finished)

parent <- parent %>% 
  rename(Pfinished = Finished) %>% 
  # ensuring that Ptime is numeric
  mutate(Ptime = as.numeric(Ptime))

# Will need to clean parent reported time data. Did so out of R for this draft, but will do it in R for the final version of this project. Find the unedited version in localonly
```

```{r wrangling a}
# merging datasets
youtube <- full_join(parent, child, by = "PID")

# removing instances where either parents or children failed to finish
youtube <- youtube %>% 
  filter(Pfinished == Cfinished) %>% 
  # excluding attention check question for now
  select(-c(`homophily-behave_5`))

# create age column
# used YouTube (funny right?)
date_today <- Sys.Date()   # Current date
youtube <- youtube %>% 
  mutate(bday = as.Date(bday, format = "%m/%d/%Y")) %>% 
  mutate(age = age_calc(
    bday,
    date_today,
    units = "years"
  ))

# merge genre and genre_8_TEXT - replace 'other' with the entry

```


```{r wrangling b}
# CATEGORICAL: Dealing with Likert scales - child survey items

# QUESTION: DO I KEEP THIS DATA ORDINAL OR TURN IT NUMERIC? 

# Making relevant items into factors and creating levels 
youtube <- youtube %>% 
  # days
  mutate(days = as_factor(days)) %>% 
  mutate(days = fct_relevel(days, c("Never", 
                "1 to 2 days a week",
                "3 to 4 days a week",
                "5 to 6 days a week",
                "Every day"))) %>% 
  # Ctime
  mutate(Ctime = as_factor(Ctime)) %>% 
  mutate(Ctime = fct_relevel(Ctime, c("About 15 minutes a day", 
                "About 30 minutes a day",
                "About 45 minutes a day",
                "About 1 hour a day",
                "About 1 and 1/2 hours a day",
                "More than 2 hours"))) %>% 
  # malleable and behavior
  mutate(
    across(c(malleable_1, malleable_2, malleable_3, malleable_4, behavior_1, behavior_2, behavior_3, behavior_4, behavior_5, behavior_6, behavior_7),
           ~ fct_relevel(as_factor(.),
             "Strongly disagree",
             "Somewhat disagree",
             "Neither agree nor disagree",
             "Somewhat agree",
             "Strongly agree"
           ))) %>% 
  # homophily and parasocial 
  mutate(
    across(c(`homophily-appear_1`, `homophily-appear_2`, `homophily-appear_3`, `homophily-appear_4`, `homophily-appear_5`, `homophily-behave_1`, `homophily-behave_2`, `homophily-behave_3`, `homophily-behave_4`, `homophily-behave_6`, parasocial_1, parasocial_2, parasocial_3, parasocial_4, parasocial_5),
           ~ fct_relevel(as_factor(.),
             "Really disagree",
             "Disagree",
             "I don't know",
             "Agree",
             "Really agree"
           )))  %>% 
  # outgroup-freq
  mutate(`outgroup-freq` = as_factor(`outgroup-freq`)) %>% 
  mutate(`outgroup-freq` = str_trim(`outgroup-freq`)) %>% 
  mutate(`outgroup-freq` = fct_relevel(`outgroup-freq`, c("Never",
                "Rarely",
                "Sometimes",
                "Often",
                "Very often")))


# not including outgroup-simple for now
```

```{r}
# NUMERIC - Dealing with Likert scales - child survey items

# Making relevant items numeric 
youtube <- youtube %>% 
  # malleable and behavior
  mutate(
    across(c(malleable_1, malleable_2, malleable_3, malleable_4, behavior_1, behavior_2, behavior_3, behavior_4, behavior_5, behavior_6, behavior_7),
           ~ recode(.,
             "Strongly disagree" = 1,
             "Somewhat disagree" = 2,
             "Neither agree nor disagree" = 3,
             "Somewhat agree" = 4,
             "Strongly agree" = 5
           ))) %>% 
  # homophily and parasocial 
  mutate(
    across(c(`homophily-appear_1`, `homophily-appear_2`, `homophily-appear_3`, `homophily-appear_4`, `homophily-appear_5`, `homophily-behave_1`, `homophily-behave_2`, `homophily-behave_3`, `homophily-behave_4`, `homophily-behave_6`, parasocial_1, parasocial_2, parasocial_3, parasocial_4, parasocial_5),
           ~ recode (.,
             "Really disagree" = 1,
             "Disagree" = 2,
             "I don't know" = 3,
             "Agree" = 4,
             "Really agree" = 5
           )))  %>% 
  # outgroup-freq
  mutate(`outgroup-freq` = recode(`outgroup-freq`, 
                "Never" = 1,
                "Rarely" = 2,
                "Sometimes" = 3,
                "Often" = 4,
                "Very often" = 5))
```


```{r}
# Dealing with Likert scales - child survey items

# Composite scores
# Racial attitudes score -- total possible score = 20
youtube <- youtube %>% 
  mutate(malleable_score = rowSums(across(malleable_1:malleable_4))) %>% 
  mutate(malleable_score = malleable_score/20)

# Parasocial relationship scores (each block separately, then aggregate)
youtube <- youtube %>% 
  # homophily-appear -- total possible score = 20
  mutate(h_appear_score = rowSums(across(`homophily-appear_1`:`homophily-appear_5`))) %>% 
  # homophily-behave -- total possible score = 20
  mutate(h_behave_score = rowSums(across(`homophily-behave_1`:`homophily-behave_6`))) %>% 
  # parasocial -- total possible score = 20
  mutate(parasocial_score = rowSums(across(parasocial_1:parasocial_5))) %>% 
  #Composite scores
  mutate(composite = rowSums(across(h_appear_score:parasocial_score))) %>% 
  # Proportion scores
  mutate(h_appear_score = h_appear_score/20) %>%
  mutate(h_behave_score = h_behave_score/20) %>%
  mutate(parasocial_score = parasocial_score/20) %>%
  mutate(composite = composite/60)

# Racial regularities score (behavior) -- total possible score = 35
youtube <- youtube %>% 
  # Reverse coded items
  mutate(across(c(behavior_3, behavior_5, behavior_7), ~ 6 - .)) %>% 
  # Score
  mutate(regularity_score = rowSums(across(behavior_1:behavior_7))) %>% 
  mutate(regularity_score = regularity_score/35)

# definitely need to calculate cronbach's alphas...

# temporary intermediate dataset
write_csv(youtube, "youtube.csv")
```

