---
title: "preparation"
author: "Reilly Amera"
date: "2025-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
# Packages
library(tidyverse)
library(eeptools)
```


```{r read-in}
# Read in data
child <- read_csv("child.csv", col_names = TRUE)
parent <- read_csv("parent.csv", col_names = TRUE)
```

```{r cleaning}
# Data Cleaning

# Remove rows that do not contain survey data
parent <- parent[-c(1, 2),]
child <- child[-c(1, 2),]

# Parent cleaning
parent <- parent %>% 
  # remove survey testing responses 
  filter(Q_CHL != "preview") %>% 
  # self consent = agree
  filter(Pconsent_self == "Agree") %>% 
  # child consent = agree
  filter(`Pconsent-child` == "Agree") %>% 
  # remove duplicates
  mutate(Q_RelevantIDDuplicate = 
           # Logical operators
           ifelse(is.na(Q_RelevantIDDuplicate), FALSE, TRUE)) %>% 
  filter(Q_RelevantIDDuplicate != TRUE) %>% 
  # filter attn checks
  filter(yt_opinions_4 == "A lot")

# Child cleaning
child <- child %>% 
  # remove survey testing responses
  filter(Q_CHL != "preview") %>% 
  # consent = yes
  filter(Cconsent == "YES") %>% 
  # filter attn checks 
  filter(homophily_behave_5 == "Agree")

# Remove unnecessary columns
parent <- parent %>% 
  select(-c(StartDate:Q_RelevantIDLastStartDate, gc:tg))
child <- child %>% 
  select(-c(StartDate:UserLanguage, opp, Q_BallotBoxStuffing:tg))

```

```{r merge}
youtube <- inner_join(parent, child, by = join_by(transaction_id))
```

```{r yt-factors}
# CATEGORICAL: Dealing with Likert scales

# Forcats

# Making relevant items into factors and creating levels 
youtube <- youtube %>% 
  # days
  mutate(days = as_factor(days)) %>% 
  mutate(days = fct_relevel(days, c("Never", 
                "1 to 2 days a week",
                "3 to 4 days a week",
                "5 to 6 days a week",
                "Every day"))) %>% 
  # Ctime
  mutate(Ctime = as_factor(Ctime)) %>% 
  mutate(Ctime = fct_relevel(Ctime, c("About 15 minutes a day", 
                "About 30 minutes a day",
                "About 45 minutes a day",
                "About 1 hour a day",
                "About 1 and 1/2 hours a day",
                "More than 2 hours"))) %>% 
  # malleable, regularities, homophily, parasocial
  mutate(
    across(c(malleable_1, malleable_2, malleable_3, malleable_4, regularities_1, regularities_2, regularities_3, regularities_4, regularities_5, regularities_6, regularities_7, `homophily_appear_1`, `homophily_appear_2`, `homophily_appear_3`, `homophily_appear_4`, `homophily_appear_5`, `homophily_behave_1`, `homophily_behave_2`, `homophily_behave_3`, `homophily_behave_4`, `homophily_behave_6`, parasocial_1, parasocial_2, parasocial_3, parasocial_4, parasocial_5),
           ~ fct_relevel(as_factor(.),
             "Really disagree",
             "Disagree",
             "I don't know",
             "Agree",
             "Really agree"
           )))  %>% 
  # outgroup-freq
  mutate(`outgroup_freq` = as_factor(`outgroup_freq`)) %>% 
  mutate(`outgroup_freq` = str_trim(`outgroup_freq`)) %>% 
  mutate(`outgroup_freq` = fct_relevel(`outgroup_freq`, c("Never",
                "Rarely",
                "Sometimes",
                "Often",
                "Very often")))

```

```{r recoding}
youtube <- youtube %>% 
  mutate(
    across(c(`homophily_appear_1`, `homophily_appear_2`, `homophily_appear_3`, `homophily_appear_4`, `homophily_appear_5`, `homophily_behave_1`, `homophily_behave_2`, `homophily_behave_3`, `homophily_behave_4`, `homophily_behave_6`, parasocial_1, parasocial_2, parasocial_3, parasocial_4, parasocial_5),
           ~ recode (.,
             "Really disagree" = 1,
             "Disagree" = 2,
             "I don't know" = 3,
             "Agree" = 4,
             "Really agree" = 5
           ))) %>% 
  mutate(
    across(c(malleable_1, malleable_2, malleable_3, malleable_4, regularities_1, regularities_2, regularities_3, regularities_4, regularities_5, regularities_6, regularities_7),
           ~ recode(.,
             "Really disagree" = 1,
             "Disagree" = 2,
             "Neither agree nor disagree" = 3,
             "Agree" = 4,
             "Really agree" = 5
           ))) %>%  
  select(-c(homophily_behave_5))
```


```{r stringr}
# Cleaning using stringr
youtube <- youtube %>% 
  # only keep last character in friend choice task
  mutate(friend = str_sub(friend, start = -1, end = -1)) %>% 
  # trim whitespace from free response
  mutate(favorite = str_squish(favorite))
```

```{r age}
# calculating child age
date_today <- Sys.Date()  
youtube <- youtube %>% 
  mutate(bday = as.Date(bday, format = "%m/%d/%Y")) %>% 
  mutate(age = age_calc(
    bday,
    date_today,
    units = "years"
  ))
```

```{r}
# Composite scores
# Racial attitudes score -- total possible score = 20
youtube <- youtube %>% 
  mutate(malleable_score = rowSums(across(malleable_1:malleable_4))) %>% 
  mutate(malleable_score = malleable_score/20)

# Parasocial relationship scores (each block separately, then aggregate)
youtube <- youtube %>% 
  # homophily-appear -- total possible score = 20
  mutate(h_appear_score = rowSums(across(`homophily-appear_1`:`homophily-appear_5`))) %>% 
  # homophily-behave -- total possible score = 20
  mutate(h_behave_score = rowSums(across(`homophily-behave_1`:`homophily-behave_6`))) %>% 
  # parasocial -- total possible score = 20
  mutate(parasocial_score = rowSums(across(parasocial_1:parasocial_5))) %>% 
  #Composite scores
  mutate(composite = rowSums(across(h_appear_score:parasocial_score))) %>% 
  # Proportion scores
  mutate(h_appear_score = h_appear_score/20) %>%
  mutate(h_behave_score = h_behave_score/20) %>%
  mutate(parasocial_score = parasocial_score/20) %>%
  mutate(composite = composite/60)

# Racial regularities score (behavior) -- total possible score = 35
youtube <- youtube %>% 
  # Reverse coded items
  mutate(across(c(behavior_3, behavior_5, behavior_7), ~ 6 - .)) %>% 
  # Score
  mutate(regularity_score = rowSums(across(behavior_1:behavior_7))) %>% 
  mutate(regularity_score = regularity_score/35)
```


```{r}
write_csv(youtube, "youtube.csv")
```

